# directions
source: ./src
destination: ./_site
plugins_dir:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - .tmp/
  - .jekyll-cache/
  - .gitignore
  - README.md
  - Rakefile
  - _config.yml
  - _config.sample.yml
  - _site
  - docs
  - src

# Site display
title: Liuying's Site
description: Personal Output
keywords: Blog, Life-long Learner, Developer, Data Visualization, Video Games
favicon: /assert/favicon.ico

# Author info
author: Liuying
email:
## social account
github: liuying-y
stackoverflow: 23873459
codepen: liuying-y
patreon: liuying_y
bilibili: 
zhihu:
juejin:
external_social:
  -
    url: 
    icon:
    alias: 
  

# Pages
pages:
  index: /
  about: 

## operations
google-analytics:
  id: ""
